### ISSUE TITLE
RestClient.conf() refactoring

### ISSUE THREAD

**Issue by ad-lebedev** [Amareis/another-rest-client#1]
Hi! Very nice little and useful library!
Just as a proposal: why not to use `Object.assign()` method in your `RestClient.conf()`?
For example, you can move your default options to the separate file, import it, and then do something like this:

``` javascript
import settings from './settings'
....
conf(options={}) {
  this._opts = Object.assign({}, settings, options)
}
```

Thanks and good luck!

**Comment by Amareis** [comment]
1. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/assign - very bad browser support. Of course, we can use polyfill, but it just gives more code without any benefits - even code readability will not be enhanced.
2. Your example has different logic. It constructs options from scratch on every call, when the current version overrides only fields, passed in `options` parameter. It matter because i think that conf() must return current options (it's not implemented now, but it will).

**Comment by ad-lebedev** [comment]
1. I don't see any problems to use one more babel polyfill, cause you already use babel.
2. `Object.assign()` do exactly what you want - overrides only fields, passed in the `options` and assigns "mixed" object to the `this._opts`. If you want to return current configuration, just do it like you did before:

``` javascript
conf(options={}) {
  this._opts = this._opts || Object.assign({}, settings, options)
}
```

**Comment by Amareis** [comment]
Humm, i thought about classic polyfill, but babel plugin - good solution.

``` js
api.conf({'x-first-mime': {encode: encodeFunc}});
api.conf({'x-second-mime': {encode: secondEncodeFunc}});
```

In current version final options includes both options, in your - only last. But it can be fixed:

``` js
conf(options={}) {
  this._opts = Object.assign(this._opts || defaults, options);
  return Object.assign({}, this._opts);
}
```

Ok, i'll do that. Thank you for good words and help.

**Comment by ad-lebedev** [comment]
As for me, it's better to do it like this:

``` javascript
conf(options={}) {
  this._opts = Object.assign({}, this._opts || defaults, options)
  return this._opts
}
```

cause in case of config initialisation, you will try to assign variable `options` to the constant (you will declare `defaults` as a `const`, will you?).
Also, I don't understand your last line, for what purpose you creates new object?

**Comment by Amareis** [comment]
About `defaults` - i think that they can be defined just in conf (cause they used only here). In that way they can be mutable.
New object created because you don't want to user suddenly changes options by change return object. Maybe we even needs deep copy here.

**Comment by Amareis** [comment]
Also, it's better to reuse old _opts object instead creating new object.
