### ISSUE TITLE
Not getting expected headers in XmlHttpRequest during a response

### ISSUE THREAD

**Issue by mmacphail** [Amareis/another-rest-client#10]
Hello,

I use the following snippet: 

        const api = new RestClient("http://localhost:8080/mgag/api");
        api.res("users");
        api.users.post(data).then(function (evt) {
            console.log(evt);
        }, function (other) {
            alert("Unable to subscribe");
            console.log(other);
            console.log(other.getAllResponseHeaders());
        });

Unfortunately, the `other` parameter doesn't contain any useful headers even if the server sends them.

What I'm getting in Mozzilla Developper Console:
![image](https://user-images.githubusercontent.com/9349702/32444948-2e7c6bf0-c2fc-11e7-8bf7-fe5574592b12.png)

![image](https://user-images.githubusercontent.com/9349702/32445095-ac8c2dbe-c2fc-11e7-96b4-caccdb5e38dd.png)

I want to grab the "Cause" header here.

Please note that I use CORS.

**Comment by Amareis** [comment]
Why you have "http://localhost:8080/app/api" URL in code, but "http://localhost:8080/mgag/app/api" URL in dev tools? Notice `/mgag/` part.

**Comment by Amareis** [comment]
Also, look here: https://stackoverflow.com/questions/8945587/xmlhttprequest-getallresponseheaders-not-returning-all-the-headers

**Comment by mmacphail** [comment]
The url is http://localhost:8080/mgag/api ; I misstype app in my question let me edit this for posterity.

Indeed, I had to expose my CORS headers and that was th problem. Thanks 👍 !

**Comment by Amareis** [comment]
If you want to thanks me, just star the repo ;)
