### ISSUE TITLE
Generate request with non-unique keys

### ISSUE THREAD

**Issue by x29a** [Amareis/another-rest-client#11]
Hi there and thanks for this library!

Is it possible to create a request with non-unique keys?

In the backend i want to use [php-crud-api](https://github.com/mevdschee/php-crud-api) which has a filter feature [which allows](https://github.com/mevdschee/php-crud-api#list--filter--satisfy) multiple `filter[]` tags to combine conditions where the request would look something like

> this.REST.endpoint.get({"filter[]": "name_id,eq," + 1337, "filter[]": "category_id,ge," + 4223, columns: "name, category, timestamp", order: "timestamp, asc" })...

results in the following XHR request:

> XHR finished loading: GET "http://localhost/api.php/endpoint?filter%5B%5D=category_id%2Cge%2C4223&columns=name%2C%20category%2C%20timestamp&order=timestamp%2C%20asc"

so the first `filter[]` part gets truncated.

Simple workaround i found was to explicetly name the indices of the array like

> this.REST.endpoint.get({"filter[0]": "name_id,eq," + 1337, "filter[1]": "category_id,ge," + 4223, columns: "name, category, timestamp", order: "timestamp, asc" }).

but i still think itd be great if the library could take care of that or forward the URL unmodified.

**Comment by Amareis** [comment]
@x29a no, you cannot make it just because JS cannot into object with non-unique keys. But i can make simple wokaround, which will allows you to pass multiple objects into `get`, so you can just make something about `this.REST.endpoint.get({"filter[]": "name_id,eq," + 1337}, "filter[]": "category_id,ge," + 4223}, {columns: "name, category, timestamp", order: "timestamp, asc" })`

**Comment by Amareis** [comment]
I'll do that today, so just wait.

**Comment by Amareis** [comment]
@x29a check 0.3.5 version
 `api.cookies.get({'filter[]': 'fresh'}, {'filter[]': 'taste'}); //GET http://example.com/cookies?filter%5B%5D=fresh&filter%5B%5D=taste`

**Comment by Amareis** [comment]
@x29a did you check this feature?

**Comment by x29a** [comment]
Yes, this works very well, thanks for incorporating it so quickly!

**Comment by Amareis** [comment]
If you want to thanks me, just star the repo ;)
