### ISSUE TITLE
Processing 'multipart/form-data' requests

### ISSUE THREAD

**Issue by Fatal1stZ** [Amareis/another-rest-client#13]
Yet another problem with this rest client is how to handle 'multipart/form-data' requests (e.g. we want to send post with files).

I was able to make formData, but the header contentType goes without boundary, so the server cannot parse the request.
```
      rest.conf( {
        contentType: 'multipart/form-data',
        'multipart/form-data': {
          encode: params => {
            return Object.keys( params ).reduce( ( formData, paramName ) => {
              formData.append( paramName, params[ paramName ] )
              return formData
            }, new FormData() )
          }
        }
      } )

      let result = await rest[ UPLOAD ].post( params )
```

Any idea how to handle it?

**Comment by Amareis** [comment]
Ok, i'll fix that. We can just don't sets any content-type and browser will handle it automatically, so I'll add check on this mime in request function.

**Comment by Amareis** [comment]
Check v0.4.2, it don't sets content type if form-data content type and FormData used.

**Comment by Fatal1stZ** [comment]
It works fine now!

**Comment by Amareis** [comment]
Good, good.
