### ISSUE TITLE
ProgressEvent

### ISSUE THREAD

**Issue by macfire** [Amareis/another-rest-client#14]
Is it possible to get the progress of a (large) JSON response?

[xhr spec](https://xhr.spec.whatwg.org/#interface-progressevents)
[xhr example](https://xhr.spec.whatwg.org/#example)

Update:
I've tried implementing the example on whatwg.org, but no success. I don't see any calls to  `onprogress` in my browser console.  Would this be something provided by the server? (I'm using Python/Flask, and doing some research there also).

```javascript
api.api().myapi()
    .get()
    .on('response', function(res) {
        console.log(res.onprogress) // returns 'null'
        res.onprogress = function(pe) {
           console.log(pe); // not reached
           if (pe.lengthComputable) {
               console.log(pe.loaded) // not reached
           }}})
     .then(function (_json) { do_stuff(_json) })
```

**Comment by Amareis** [comment]
You need to listens `request` event, not `response`, because `response` firing after downloading completed.

**Comment by Amareis** [comment]
Your server should set `Content-Length` header for working `lengthComputable`, `loaded` and `total` XHR properties.

**Comment by macfire** [comment]
Thanks. I'll find out how to set `Content-Length` header and try again.

**Comment by macfire** [comment]
I did discover that the `Content-Length` is already being set.  I tried putting the code in `api.on('request')`, but the `onprogress` method is not available.

I am going to close this thread for now. If I find a solution, I'll comment here.
