### ISSUE TITLE
Axios instead XMLHttpRequest

### ISSUE THREAD

**Issue by goodok21** [Amareis/another-rest-client#18]
I have some troubles with Authorization headers in XMLHttpRequest using Auth0. When I try to renew token from Auth0 after page loaded with this code:

```
api.on('request', xhr => {
  xhr.setRequestHeader('Authorization', `Bearer ${authResult.accessToken}`);
})
```

I expect that new token will replace the old one, but it's add like: `Bearer OLDTOKEN, NEWTOKEN`.

Can you help with replace XMLHttpRequest or provide example how to use tokens and when and how I should replace it?

**Comment by Amareis** [comment]
Does you sure about `authResult.accessToken` value? If you log it just before `xhr.setRequestHeader` call, which result appears in console?

**Comment by goodok21** [comment]
Yes I’am sure about accessToken value, JWT token appears in console. The problem is that we can’t replace exist token in authorization header when using XMLHttpRequest, just add a new values comma-separated. So I asked about possibility to change XMLHttpRequest to Axios

**Comment by goodok21** [comment]
sorry, I just find it out.

to add header in current api request:

```
api.posts(id).get()
.on('request', xhr => {
  xhr.setRequestHeader('Authorization', `Bearer ${token}`)
})
.then(response => { ...do smth })
```
