### ISSUE TITLE
Abort XHR?

### ISSUE THREAD

**Issue by GRiMe2D** [Amareis/another-rest-client#3]
In current project I heavily use your library. Sometimes I need to abort opened xhr requests. 

I think you could add one time event listeners. Look at this

``` javascript
...

let openedXHR = [];
api.once('request', (xhr) => {
    openedXHR.push(xhr);
})
api.res('account').res('balance').get().then(...)

openedXHR.forEach((xhr) => xhr.abort())
```

I can't use `request` event, because `RestClient` created once and reused everywhere.

**Comment by Amareis** [comment]
So, i'm back in programmer's world, and now it's time to rise ARC again. Can you say more detail about it issue?

**Comment by Amareis** [comment]
Now you can use this:
```js
api.res('account').res('balance').get().on('request', xhr => openedXHR.push(xhr));
```
