### ISSUE TITLE
Firefox: SyntaxError: JSON.parse: unexcepted...

### ISSUE THREAD

**Issue by HassanHeydariNasab** [Amareis/another-rest-client#5]
```
var r = new RestClient('http://127.0.0.1:8080', {contentType: 'json'});
r.res('test')
r.test('ttt').get().then(function(k){alert(k)})
```

Chromium:
It works properly!

Firefox:
http://127.0.0.1:8080/test/ttt works properly. but when I use another-rest-client, It says:
`SyntaxError: JSON.parse: unexcepted end of data at line 1 column 1 of the JSON data`
but when I click on "edit and resend" and click on "send" without any change on headers, it return correct json in the response section without "SyntaxError: JSON.parse: unexcepted end of data at line 1 column 1 of the JSON data"

I'm using Bottle on Python as backend.

**Comment by Amareis** [comment]
Strange error. Can you say something about it now, or i close it as too old?

**Comment by Amareis** [comment]
Okay, i made some error handling for this case
