### ISSUE TITLE
What is about camelize / decamelize config?

### ISSUE THREAD

**Issue by byzg** [Amareis/another-rest-client#8]
As I can see I cant decamelize request params without own wrapper like 
```javascript
this.api['groups'].post(decamelizeKeys(data)).then(response => {
  return camelizeKeys(response)
})
```
for each action

**Comment by Amareis** [comment]
@byzg: Will it ok if you will get `data` object in `request` event?

**Comment by byzg** [comment]
@Amareis  sorry I've just found https://github.com/Amareis/another-rest-client/issues/2
it solves the issue
